### PR TITLE
Adds ability to modify click modular router via command line

### PR DESCRIPTION
**Pull request by isi-lincoln**
Unlike previous scenarios which required users to configure an magi agent configuration file (.aal).  This PR adds the ability to generically modify click internals through command line options to modify_click.py.

Inputs can be passed through options, interactively (prompt/response), and through a file to ease the process of click configuration.  This will allow TA1 performers to wrap calls to modify_click.py with other high level functionality, such as setting up timers to create more dynamic scenarios.

This PR however is not 100% functional until it can be verified that click is being modified (tested at an earlier date with previous version of code), and that the modify_click.py help commands are able to correctly parse the magi daemon logs.  At the moment this is not possible due to an saturation of resources capable of running click in dpdk mode.

Lincoln

### CODE REVIEW

**Comment by isi-lincoln** [comment]
Let me know if it is preferable to squash the commits down into a few commits with more apt descriptions.

**Comment by isi-lincoln** [comment]
This code is all working - verified that it can be run on both users.isi.deterlab.net and on control.proj.exp.isi.... servers.

Once this is approved, can @glawler approve the changes to magi_modules so this code will be functional for all users.

Then will change the templates from using my magi_module version, to point to current.

**Comment by isi-lincoln** [comment]
After last commit:

```[lthurlow@users ~/scenarios/modify_click]$ ./modify_click.py 
2
usage: modify_click.py [-h] (-i | -f FILE_INPUT | -c MSG ELEMENT KEY VALUE)
                       [-e EXPERIMENT] [-p PROJECT] [-y]
                       [--control CONTROL HOSTNAME] [--click CLICK HOSTNAME]
                       [-v] [--version]
modify_click.py: error: one of the arguments -i/--interactive -f/--file -c/--cmdline is required
[lthurlow@users ~/scenarios/modify_click]$ ./modify_click.py -i -v
2
2018-01-19 09:25:33,375 [DEBUG] py2_wrapper: Namespace(click_server=False, cmdline=False, control_server=False, experiment=False, file_input=None, ignore=False, interactive=True, project=False, verbose=True)
Use \h for available values - there is a delay with using help
Project Name?
(project) > \h   
edgect
test
Project Name?
(project) > edgect
Project Name is edgect? ([y]/n) 
2018-01-19 09:25:40,043 [DEBUG] py2_wrapper: project set to "edgect"
Experiment Identifier?
(experiment id) > simple
Experiment ID = simple? ([y]/n) 
2018-01-19 09:25:42,401 [DEBUG] py2_wrapper: experiment set to "simple"
click server hostname? 
(click_server) [default=vrouter] > 
click server hostname is vrouter? ([y]/n) 
2018-01-19 09:25:43,697 [DEBUG] py2_wrapper: click server hostname set to "vrouter"
control server hostname? 
(control_server) [default=control] > 
control server hostname is control? ([y]/n) 
2018-01-19 09:25:44,505 [DEBUG] py2_wrapper: control server hostname set to "control"
Click Element:
(element) > \h
2018-01-19 09:25:45,737 [DEBUG] py2_wrapper: creating template
2018-01-19 09:25:45,741 [DEBUG] py2_wrapper: /tmp/generated_click_template.aal {u'msg': u'print_elements', u'value': u'recycling', u'key': u'garbage', u'element': u'aaaaaaaaaaaaaaa_1_aaaaaaaaaaaaaaaaa'}
2018-01-19 09:25:45,742 [DEBUG] py2_wrapper: write finished - template updated
Notice: this script is going to access magi logs.  This may take a while.
 Make sure your experiment is swapped in, magi is running on the click node.
 If you need assistances, please email lincoln@isi.edu.

2018-01-19 09:25:53,282 [DEBUG] py2_wrapper: stream groupBuildS... : sent : (09:25:51) joinGroup click_group --> __ALL__ 
stream groupBuildS... : trig : (09:25:51) trigger completed: GroupBuildDone: {'group': 'click_group'}
stream groupBuildS... : sent : (09:25:51) groupPing(['click_group']) --> click_group 
stream groupBuildS... : trig : (09:25:51) trigger completed: GroupPong: {'group': 'click_group'}
stream groupBuildS... : DONE : (09:25:51) complete.
stream loadAgentSt... : sent : (09:25:51) loadAgent ClickAgent --> click_group 
stream loadAgentSt... : trig : (09:25:52) trigger completed: AgentLoadDone: {'agent': 'ClickAgent'}
stream loadAgentSt... : DONE : (09:25:52) complete.
stream start          : sent : (09:25:52) updateClickConfig(['user_inputs',  'li ... ) --> click_group 
stream start          : DONE : (09:25:52) complete.

2018-01-19 09:25:53,282 [DEBUG] py2_wrapper: 01-19 09:25:47.102 __main__                       INFO     set log level to info (20)
01-19 09:25:47.117 magi.orchestrator.parse        INFO     Incoming event triggers is a subset of outgoing event triggers
01-19 09:25:47.129 __main__                       INFO     Making sure Magi daemons are up and listening
01-19 09:25:47.129 root                           INFO     Node Set: set(['vrouter'])
01-19 09:25:47.138 magi.messaging.transportTCP    INFO     connect localhost:18808
01-19 09:25:47.139 magi.messaging.transportTCP    INFO     If connection fails, it will retry shortly.
01-19 09:25:47.188 magi.messaging.worker          INFO     Worker started. Thread id: 24118
01-19 09:25:47.389 magi.messaging.worker          INFO     Request to add new transport TCPTransport localhost:18808 to map keepConnected: True
01-19 09:25:47.389 magi.messaging.worker          INFO     Request to add new transport TCPTransport localhost:18808 to map keepConnected: True
01-19 09:25:47.389 magi.messaging.routerGroup     INFO     added transport TCPTransport localhost:18808, init rxgroup to: {}
01-19 09:25:47.390 magi.messaging.routerGroup     INFO     Sending transport add message In:None,Out:[4] (msgid:0,flags:0x0,conttype:5) src:dock - None:None --> dstgroups:set(['__NEIGH__']), dstnodes: set([]), dstdocks: set(['__GROUPS__']) = data: {resend: true}

01-19 09:25:47.810 root                           INFO     Node vrouter
01-19 09:25:48.812 __main__                       INFO     All magi daemons are up and listening
01-19 09:25:48.814 magi.messaging.transportTCP    INFO     connect localhost:18808
01-19 09:25:48.815 magi.messaging.transportTCP    INFO     If connection fails, it will retry shortly.
01-19 09:25:48.839 magi.messaging.worker          INFO     Worker started. Thread id: 24122
01-19 09:25:49.040 magi.messaging.worker          INFO     Request to add new transport TCPTransport localhost:18808 to map keepConnected: True
01-19 09:25:49.040 magi.messaging.worker          INFO     Request to add new transport TCPTransport localhost:18808 to map keepConnected: True
01-19 09:25:49.040 magi.messaging.routerGroup     INFO     added transport TCPTransport localhost:18808, init rxgroup to: {}
01-19 09:25:49.041 magi.messaging.routerGroup     INFO     Sending transport add message In:None,Out:[6] (msgid:0,flags:0x0,conttype:5) src:dock - None:None --> dstgroups:set(['__NEIGH__']), dstnodes: set([]), dstdocks: set(['__GROUPS__']) = data: {resend: true}

01-19 09:25:49.827 magi.db.Connection             ERROR    Could not connect to mongodb server on localhost:27017
01-19 09:25:49.828 magi.orchestrator.OrchestratorDisplay ERROR    Cannot initialize database: Could not connect to mongodb server on localhost:27017
01-19 09:25:50.830 magi.db.Connection             ERROR    Could not connect to mongodb server on localhost:27017
01-19 09:25:50.830 magi.orchestrator.orchestrator ERROR    Cannot initialize database: Could not connect to mongodb server on localhost:27017
01-19 09:25:50.931 magi.orchestrator.orchestrator INFO     Running Initialization Streams
01-19 09:25:52.143 magi.orchestrator.orchestrator INFO     Running Event Streams

CheckIPHeader@37
CheckIPHeader@39
CheckIPHeader@41
CoDel@33
CoDel@35
Discard@46
Discard@48
Discard@50
EtherEncap@43
EtherEncap@44
FromDPDKDevice@7
FromHost@9
ICMPError@25
ICMPError@27
ICMPError@29
ICMPError@31
Print@45
Print@47
Print@49
SetTimestamp@32
SetTimestamp@34
Strip@36
Strip@38
Strip@40
VLANDecap@8
ar1
ar2
arpq1
arpq2
arpt
c1
c2
chost
click_driver@@ControlSocket
link_1_2_bw
link_1_2_loss
link_1_2_queue
link_2_1_bw
link_2_1_loss
link_2_1_queue
out1
out2
outDPDK0
r1ttl_2
r1ttl_out_e1
r2ttl_1
r2ttl_out_e2
router1
router2
toh
vlanmux

Click Element:
(element) > link_1_2_bw
set click_element to link_1_2_bw? ([y]/n) 
2018-01-19 09:26:01,914 [DEBUG] py2_wrapper: element set to "link_1_2_bw"
Element Key (to change):
(key) > \h
2018-01-19 09:26:04,139 [DEBUG] py2_wrapper: creating template
2018-01-19 09:26:04,140 [DEBUG] py2_wrapper: /tmp/generated_click_template.aal {u'msg': u'print_keys', u'value': u'recycling', u'key': u'aaaaaaaaaaaaaaa_1_aaaaaaaaaaaaaaaaa', u'element': 'link_1_2_bw'}
2018-01-19 09:26:04,141 [DEBUG] py2_wrapper: write finished - template updated
Notice: this script is going to access magi logs.  This may take a while.
 Make sure your experiment is swapped in, magi is running on the click node.
 If you need assistances, please email lincoln@isi.edu.

2018-01-19 09:26:11,324 [DEBUG] py2_wrapper: stream groupBuildS... : sent : (09:26:09) joinGroup click_group --> __ALL__ 
stream groupBuildS... : trig : (09:26:09) trigger completed: GroupBuildDone: {'group': 'click_group'}
stream groupBuildS... : sent : (09:26:09) groupPing(['click_group']) --> click_group 
stream groupBuildS... : trig : (09:26:09) trigger completed: GroupPong: {'group': 'click_group'}
stream groupBuildS... : DONE : (09:26:09) complete.
stream loadAgentSt... : sent : (09:26:09) loadAgent ClickAgent --> click_group 
stream loadAgentSt... : trig : (09:26:10) trigger completed: AgentLoadDone: {'agent': 'ClickAgent'}
stream loadAgentSt... : DONE : (09:26:10) complete.
stream start          : sent : (09:26:10) updateClickConfig(['user_inputs',  'li ... ) --> click_group 
stream start          : DONE : (09:26:10) complete.

2018-01-19 09:26:11,324 [DEBUG] py2_wrapper: 01-19 09:26:05.203 __main__                       INFO     set log level to info (20)
01-19 09:26:05.218 magi.orchestrator.parse        INFO     Incoming event triggers is a subset of outgoing event triggers
01-19 09:26:05.230 __main__                       INFO     Making sure Magi daemons are up and listening
01-19 09:26:05.230 root                           INFO     Node Set: set(['vrouter'])
01-19 09:26:05.239 magi.messaging.transportTCP    INFO     connect localhost:18808
01-19 09:26:05.239 magi.messaging.transportTCP    INFO     If connection fails, it will retry shortly.
01-19 09:26:05.252 magi.messaging.worker          INFO     Worker started. Thread id: 24147
01-19 09:26:05.453 magi.messaging.worker          INFO     Request to add new transport TCPTransport localhost:18808 to map keepConnected: True
01-19 09:26:05.453 magi.messaging.worker          INFO     Request to add new transport TCPTransport localhost:18808 to map keepConnected: True
01-19 09:26:05.453 magi.messaging.routerGroup     INFO     added transport TCPTransport localhost:18808, init rxgroup to: {}
01-19 09:26:05.454 magi.messaging.routerGroup     INFO     Sending transport add message In:None,Out:[4] (msgid:0,flags:0x0,conttype:5) src:dock - None:None --> dstgroups:set(['__NEIGH__']), dstnodes: set([]), dstdocks: set(['__GROUPS__']) = data: {resend: true}

01-19 09:26:05.865 root                           INFO     Node vrouter
01-19 09:26:06.867 __main__                       INFO     All magi daemons are up and listening
01-19 09:26:06.868 magi.messaging.transportTCP    INFO     connect localhost:18808
01-19 09:26:06.869 magi.messaging.transportTCP    INFO     If connection fails, it will retry shortly.
01-19 09:26:06.877 magi.messaging.worker          INFO     Worker started. Thread id: 24151
01-19 09:26:07.078 magi.messaging.worker          INFO     Request to add new transport TCPTransport localhost:18808 to map keepConnected: True
01-19 09:26:07.078 magi.messaging.worker          INFO     Request to add new transport TCPTransport localhost:18808 to map keepConnected: True
01-19 09:26:07.078 magi.messaging.routerGroup     INFO     added transport TCPTransport localhost:18808, init rxgroup to: {}
01-19 09:26:07.079 magi.messaging.routerGroup     INFO     Sending transport add message In:None,Out:[3] (msgid:0,flags:0x0,conttype:5) src:dock - None:None --> dstgroups:set(['__NEIGH__']), dstnodes: set([]), dstdocks: set(['__GROUPS__']) = data: {resend: true}

01-19 09:26:07.877 magi.db.Connection             ERROR    Could not connect to mongodb server on localhost:27017
01-19 09:26:07.877 magi.orchestrator.OrchestratorDisplay ERROR    Cannot initialize database: Could not connect to mongodb server on localhost:27017
01-19 09:26:08.879 magi.db.Connection             ERROR    Could not connect to mongodb server on localhost:27017
01-19 09:26:08.880 magi.orchestrator.orchestrator ERROR    Cannot initialize database: Could not connect to mongodb server on localhost:27017
01-19 09:26:08.980 magi.orchestrator.orchestrator INFO     Running Initialization Streams
01-19 09:26:10.184 magi.orchestrator.orchestrator INFO     Running Event Streams

bandwidth
class
config
home_thread
latency
name
ports
scheduled
size
tickets

Element Key (to change):
(key) > latency
set key to latency? ([y]/n) 
2018-01-19 09:26:16,400 [DEBUG] py2_wrapper: key set to "latency"
set "latency" to what value:
(value) > 10ms
set "latency" to 10ms? ([y]/n) 
2018-01-19 09:26:21,086 [DEBUG] py2_wrapper: key set to "10ms"
2018-01-19 09:26:21,087 [INFO] py2_wrapper: {u'control_server': u'control', u'value': '10ms', u'element': 'link_1_2_bw', u'project': 'edgect', u'experiment': 'simple', u'key': 'latency', u'msg': u'user_inputs', u'click_server': u'vrouter'}
2018-01-19 09:26:21,087 [DEBUG] py2_wrapper: config file after inputs: {u'control_server': u'control', u'value': '10ms', u'element': 'link_1_2_bw', u'project': 'edgect', u'experiment': 'simple', u'key': 'latency', u'msg': u'user_inputs', u'click_server': u'vrouter'}
2018-01-19 09:26:21,087 [DEBUG] py2_wrapper: config with cmd line options: {u'control_server': u'control', u'value': '10ms', u'element': 'link_1_2_bw', u'project': 'edgect', u'experiment': 'simple', u'key': 'latency', u'msg': u'user_inputs', u'click_server': u'vrouter'}
2018-01-19 09:26:21,088 [DEBUG] py2_wrapper: creating template
2018-01-19 09:26:21,088 [DEBUG] py2_wrapper: /tmp/generated_click_template.aal {u'control_server': u'control', u'value': '10ms', u'element': 'link_1_2_bw', u'project': 'edgect', u'experiment': 'simple', u'key': 'latency', u'msg': u'user_inputs', u'click_server': u'vrouter'}
2018-01-19 09:26:21,089 [DEBUG] py2_wrapper: write finished - template updated
2018-01-19 09:26:21,683 [DEBUG] py2_wrapper: 
2018-01-19 09:26:21,684 [DEBUG] py2_wrapper: 
2018-01-19 09:26:28,724 [DEBUG] py2_wrapper: stream groupBuildS... : sent : (09:26:26) joinGroup click_group --> __ALL__ 
stream groupBuildS... : trig : (09:26:26) trigger completed: GroupBuildDone: {'group': 'click_group'}
stream groupBuildS... : sent : (09:26:26) groupPing(['click_group']) --> click_group 
stream groupBuildS... : trig : (09:26:27) trigger completed: GroupPong: {'group': 'click_group'}
stream groupBuildS... : DONE : (09:26:27) complete.
stream loadAgentSt... : sent : (09:26:27) loadAgent ClickAgent --> click_group 
stream loadAgentSt... : trig : (09:26:27) trigger completed: AgentLoadDone: {'agent': 'ClickAgent'}
stream loadAgentSt... : DONE : (09:26:27) complete.
stream start          : sent : (09:26:27) updateClickConfig(['user_inputs',  'li ... ) --> click_group 
stream start          : DONE : (09:26:27) complete.

2018-01-19 09:26:28,725 [DEBUG] py2_wrapper: 01-19 09:26:22.607 __main__                       INFO     set log level to info (20)
01-19 09:26:22.622 magi.orchestrator.parse        INFO     Incoming event triggers is a subset of outgoing event triggers
01-19 09:26:22.634 __main__                       INFO     Making sure Magi daemons are up and listening
01-19 09:26:22.634 root                           INFO     Node Set: set(['vrouter'])
01-19 09:26:22.643 magi.messaging.transportTCP    INFO     connect localhost:18808
01-19 09:26:22.643 magi.messaging.transportTCP    INFO     If connection fails, it will retry shortly.
01-19 09:26:22.655 magi.messaging.worker          INFO     Worker started. Thread id: 24197
01-19 09:26:22.856 magi.messaging.worker          INFO     Request to add new transport TCPTransport localhost:18808 to map keepConnected: True
01-19 09:26:22.856 magi.messaging.worker          INFO     Request to add new transport TCPTransport localhost:18808 to map keepConnected: True
01-19 09:26:22.857 magi.messaging.routerGroup     INFO     added transport TCPTransport localhost:18808, init rxgroup to: {}
01-19 09:26:22.858 magi.messaging.routerGroup     INFO     Sending transport add message In:None,Out:[4] (msgid:0,flags:0x0,conttype:5) src:dock - None:None --> dstgroups:set(['__NEIGH__']), dstnodes: set([]), dstdocks: set(['__GROUPS__']) = data: {resend: true}

01-19 09:26:23.269 root                           INFO     Node vrouter
01-19 09:26:24.270 __main__                       INFO     All magi daemons are up and listening
01-19 09:26:24.272 magi.messaging.transportTCP    INFO     connect localhost:18808
01-19 09:26:24.275 magi.messaging.transportTCP    INFO     If connection fails, it will retry shortly.
01-19 09:26:24.280 magi.messaging.worker          INFO     Worker started. Thread id: 24201
01-19 09:26:24.480 magi.messaging.worker          INFO     Request to add new transport TCPTransport localhost:18808 to map keepConnected: True
01-19 09:26:24.481 magi.messaging.worker          INFO     Request to add new transport TCPTransport localhost:18808 to map keepConnected: True
01-19 09:26:24.481 magi.messaging.routerGroup     INFO     added transport TCPTransport localhost:18808, init rxgroup to: {}
01-19 09:26:24.482 magi.messaging.routerGroup     INFO     Sending transport add message In:None,Out:[7] (msgid:0,flags:0x0,conttype:5) src:dock - None:None --> dstgroups:set(['__NEIGH__']), dstnodes: set([]), dstdocks: set(['__GROUPS__']) = data: {resend: true}

01-19 09:26:25.280 magi.db.Connection             ERROR    Could not connect to mongodb server on localhost:27017
01-19 09:26:25.281 magi.orchestrator.OrchestratorDisplay ERROR    Cannot initialize database: Could not connect to mongodb server on localhost:27017
01-19 09:26:26.283 magi.db.Connection             ERROR    Could not connect to mongodb server on localhost:27017
01-19 09:26:26.283 magi.orchestrator.orchestrator ERROR    Cannot initialize database: Could not connect to mongodb server on localhost:27017
01-19 09:26:26.384 magi.orchestrator.orchestrator INFO     Running Initialization Streams
01-19 09:26:27.588 magi.orchestrator.orchestrator INFO     Running Event Streams```

```lthurlow@server1:~$ ping -i 2 server2
PING server2-lan2 (10.2.1.1) 56(84) bytes of data.
64 bytes from server2-lan2 (10.2.1.1): icmp_seq=1 ttl=60 time=295 ms
64 bytes from server2-lan2 (10.2.1.1): icmp_seq=2 ttl=60 time=273 ms
64 bytes from server2-lan2 (10.2.1.1): icmp_seq=4 ttl=60 time=272 ms
.....
64 bytes from server2-lan2 (10.2.1.1): icmp_seq=32 ttl=60 time=273 ms
64 bytes from server2-lan2 (10.2.1.1): icmp_seq=33 ttl=60 time=273 ms
64 bytes from server2-lan2 (10.2.1.1): icmp_seq=34 ttl=60 time=33.1 ms
64 bytes from server2-lan2 (10.2.1.1): icmp_seq=35 ttl=60 time=33.2 ms
64 bytes from server2-lan2 (10.2.1.1): icmp_seq=36 ttl=60 time=33.0 ms
^C
--- server2-lan2 ping statistics ---
36 packets transmitted, 34 received, 5% packet loss, time 70075ms
rtt min/avg/max/mdev = 33.000/254.431/333.434/69.684 ms```

Interactive working correctly.

**Comment by isi-lincoln** [comment]
@ekline2 @gbartlet ready for Merge.

**Review by gbartlet — APPROVED** [review]
Looks good! In the future, when we come back to this, we should look at generalizing the aal creation etc. to other MAGI modules and reduce the one-off checking of things that we *should* be able to get from MAGI/DETER (and not directly from assumed directory structure etc.).

**Comment by isi-lincoln** [comment]
I am going to open/track that issue with MAGI MODULES.  I think that for scenarios the issues will be with what users are breaking with modify_click, and how to limit those issues (enforce control host, enforce running on control host, using MAGI messages to implicitly learn the experiment, etc)

**Pull request merged**
